### ISSUE TITLE
SASL Authentication ?

### ISSUE THREAD

**Issue by zx8086** [Consdata/kouncil#264]
For a production cluster....

**Comment by miguelbaldi** [comment]
Works for me pretty well.
Example configuration:
```yaml
kouncil:
    clusters:
      - name: localhost 
        kafka:
          properties:
            security:
              protocol: SASL_PLAINTEXT
            sasl:
              mechanism: SCRAM-SHA-256
              jaas:
                config: org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";
        brokers:
          - host: localhost
            port: 9092
```
